apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: gcp-template
  title: Google Cloud Platform infrastructure template
  description: Create a simple GCP stack
  tags:
    - gcp
    - gke
spec:
  owner: diego.braga@kiratech.it
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this service does.
      http_port:
        title: Port
        type: integer
        default: 8080
        description: The port to run the gRPC service on
