apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: gcp-template
  title: Google Cloud Platform infrastructure template
  description: Create a simple GCP stack
  tags:
    - gcp
    - gke
spec:
  owner: diego.braga86@gmail.com
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - component_id
      - description
      - networkRef
      - clusterRef
      - clusterNodesCount
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
      description:
        title: Description
        type: string
        description: Help others understand what this service does.
      networkRef:
        title: Network identifier
        type: string
        description: Network identifier
      clusterRef:
        title: Cluster identifier
        type: string
        description: Cluster identifier
      clusterNodesCount:
        title: Number of nodes of the cluster per region
        type: integer
        description: Number of nodes of the cluster per region
