apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: gcp-template
  title: Google Cloud Platform infrastructure template
  description: Create a simple GCP stack
  tags:
    - gcp
    - gke
spec:
  owner: diego.braga@kiratech.it
  templater: cookiecutter
  type: service
  path: '.'
  schema:
    required:
      - nodes-count 
      - nodes-size 
    properties:
      nodes-count:
        title: Number of nodes of the GKE cluster
        type: integer
        description: Number of nodes of the GKE cluster 
      nodes-size:
        title: Size of nodes of the GKE cluster 
        type: integer
        default: 3
        description: Size of nodes of the GKE cluster
