name: Release Charts

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create ArgoCD application
        run: |
          curl -v -k --fail --location \
          --request POST 'https://argocd.projectx.kiratech.biz/api/v1/applications' \
          --header 'Content-Type: application/json' \
          --header 'Cookie: argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5MDE1Zjk3Zi1iZGRjLTQ3ZDYtYmIxMS1lNjVhMmViODA0NWMiLCJpYXQiOjE2MTIzNTc4NjAsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTYxMjM1Nzg2MCwic3ViIjoiYmFja3N0YWdlIn0.aebO2zwmgAcHPCFdf6WuC_MdxCtOIxVPOZvzBCeOIYA' \
          --data-raw '{
              "metadata": {
                  "name": "{{cookiecutter.component_id}}"
              },
              "spec": {
                  "source": {
                      "repoURL": "{{cookiecutter.storePath}}",
                      "path": "charts/"
                  },
                  "destination": {
                      "namespace": "{{cookiecutter.component_id}}",
                      "server": "https://lokomotive-cluster.projectx.kiratech.biz:6443"
                  },
                  "syncPolicy": {
                      "syncOptions": [
                          "CreateNamespace=true"
                      ],
                      "automated": {
                          "allowEmpty": true,
                          "prune": false,
                          "selfHeal": false
                      }
                  }
              }
          }'
