apiVersion: gcp.platformref.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: {{cookiecutter.clusterRef}}
  labels:
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  compositionSelector:
    matchLabels:
      provider: gcp-stack-template-provider
  id: {{cookiecutter.clusterRef}}
  parameters:
    nodes:
      count: {{cookiecutter.clusterNodesCount}}
      size: small
    services:
      operators:
        prometheus:
          version: "10.0.2"
    networkRef:
      id: {{cookiecutter.networkRef}}
  writeConnectionSecretToRef:
    name: cluster-conn
