apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: {{cookiecutter.cloudSqlRef}}
  labels:
    backstage.io/kubernetes-id: {{cookiecutter.component_id}}
spec:
  forProvider:
    databaseVersion: {{cookiecutter.cloudSqlDatabaseVersion}}
    region: {{cookiecutter.cloudSqlRegion}}
    settings:
      tier: {{cookiecutter.cloudSqlTier}}
      dataDiskType: {{cookiecutter.cloudSqlDataDiskType}}
      dataDiskSizeGb: {{cookiecutter.cloudSqlDataDiskSizeGb}}
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: cloudsqlpostgresql-conn
  providerConfigRef:
    name: gcp-stack-template-provider
